### ISSUE TITLE
lang:Forth

### ISSUE THREAD

**Issue by larsbrinkhoff** [boyter/searchcode#24]
Is there a way to search Forth code?

E.g. like https://github.com/search?l=Forth&q=metacompiler&type=Code

**Comment by boyter** [comment]
It should be possible by specifying it like so https://searchcode.com/?q=math+lang%3Aforth but it seems nothing exists. I'll have a look in the database but its possible I'm missing forth totally.

Do you know the file extension usually used for forth? You can specify the extension like so https://searchcode.com/?q=math+ext%3Apy for the moment.

I'll add forth if you could possibly help me write the code to identify it. Sorry but I know nothing about forth so would need a little help.

-----Original Message-----

**Comment by larsbrinkhoff** [comment]
Sure, I'll help!  I've been [working with GitHub's Linguist](https://github.com/github/linguist/search?q=forth+author%3Alarsbrinkhoff&type=Issues) to improve their Forth detection.

Common file extensions are: fth, fs, 4th, frt, f, fr, 4, fi, forth, ft.  These are mostly supported by GitHub.  Note that there are conflicts with F#, Fortran, GLSL, and Filterscript.  Sigh.

I did try `dup swap ext:fs` but there were surprisingly few hits.  See e.g. https://github.com/search?q=dup+swap+extension%3Afs

**Comment by boyter** [comment]
Great! Yes it seems it tends to get picked up as F# as you say rather then Forth. I currently use Cloc (http://cloc.sourceforge.net/) for the language recognition, but I do have some crude ability to pick other languages. If you could provide just a few keywords that would make you fairly sure I am dealing with forth file (or whatever you think appropriate) ill add it to the pipeline. Once done I will queue some reindexes of your chosen repositories and it should be populated for you to have a look. How does that sound?

The limited results might be down to just not indexing enough, or that the file type was listed as unknown and not indexed at all (I need to be slightly selective as I don't have as much hardware as others). I will have to chase this up though to be 100% sure.

**Comment by boyter** [comment]
Accidentally closed. Sorry about that.

**Comment by larsbrinkhoff** [comment]
Forth keywords usually at the beginning of a line would be caught by the regexp `^(:|\\|create|defer|include|variable)`.  Other keywords include `value`, `constant`, `vocabulary`, `forth`, `only`, `also`, `previous`, `definitions`, `postpone`, `immediate`, `@`, `>r`, `r>`, `does>`, `[']`.

These are all delimited by whitespace, or the beginning/end of a line.  Also, they are case insensitive.

**Comment by boyter** [comment]
Sounds like a good start. I will add that in. Do you have any repositories that you know to contain forth code I can use for testing?

**Comment by larsbrinkhoff** [comment]
Well, one of my own:
https://github.com/larsbrinkhoff/lbForth

Thanks!

**Comment by boyter** [comment]
Perfect! I will start playing around with this and ask for some feedback when done.

**Comment by boyter** [comment]
I have rolled out some changes which should start adding this. I have also queued the following repo to be processed https://github.com/larsbrinkhoff/lbForth

Will let you know here the moment it has been indexed. Will be curious to see how many false positives it picks up. Hopefully its not too many.

**Comment by larsbrinkhoff** [comment]
Thanks!  Looking forward to it.

**Comment by larsbrinkhoff** [comment]
I guess it should have been indexed by now?

**Comment by boyter** [comment]
Yes it should! However.... muphy's law took hold and everything broke while I was off hiking. I am cleaning up the mess and should have it indexed soonish. Will comment back the moment its done. Sorry about that... maybe I was premature to comment till it was actually in the index.

**Comment by larsbrinkhoff** [comment]
The index is still beyond the black stump?

**Comment by boyter** [comment]
Sorry yes... well slightly. I being a developer got distracted with some other shiny things, which was trying to make the site have enough revenue to support itself. That done, I am looking at this again.

I have started the indexers again. Sorry about how long this has taken.

**Comment by larsbrinkhoff** [comment]
No problem, I know how it is.  Just a gentle reminder.

**Comment by boyter** [comment]
Just updating to say over 500,000 projects have been processed. Still 500,000 more to go, but the Forth results are finally starting to appear,

https://searchcode.com/?q=forth&loc=0&loc2=10000&lan=181

**Comment by larsbrinkhoff** [comment]
Cool!

I know this is never going to be perfect, but if you'd like to take a look, most of these are misclassified as Fortran 77:
https://searchcode.com/?q=dup+swap&loc=0&loc2=10000&lan=26

Thanks for taking the time to support a fringe language like Forth!

**Comment by boyter** [comment]
Yep that's just because they have not been reprocessed yet. I am attempting to reindex everything at which point they should be picked up correctly. 

No problem at all! Hope you find it useful in some way. Im going to close this ticket but I will continue to update the index for you.

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Comment by larsbrinkhoff** [comment]
Has the index finished updating now?  I checked these two searches; they have not picked up the Forth classification:

https://searchcode.com/?q=dup+swap&loc=0&loc2=10000&lan=26
https://searchcode.com/?q=dup+swap&loc=0&loc2=10000&lan=150

**Comment by boyter** [comment]
Still processing sorry. I tend to update the code in chunks of about 1,000,000 projects or so. I think its about half way through.

**Comment by larsbrinkhoff** [comment]
Ok, thanks for the update!
