### ISSUE TITLE
In code_search_I API, next_page field doesn't correctly signal end-of-data

### ISSUE THREAD

**Issue by njsmith** [boyter/searchcode#27]
On [this page](https://searchcode.com/api/) it says:

```
    nextpage     Id of the offset of the next page. If no next page is available it will be set to null. This is a zero based index.
```

As far as I can tell, though, `nextpage` never gets set to `null` -- it's always currentpage + 1. The only seemingly reliable way that I've found to fetch all searchcode.com results is to keep fetching the next page until you get a page with no results.

For example:

```
In [39]: json.loads(requests.get("https://searchcode.com/api/codesearch_I/?q=PyUFuncObject&per_page=100&p=6", verify=False).text)["nextpage"]
Out[39]: 7

In [40]: json.loads(requests.get("https://searchcode.com/api/codesearch_I/?q=PyUFuncObject&per_page=100&p=7", verify=False).text)
Out[40]: 
{u'language_filters': [{u'count': 643, u'id': 28, u'language': u'C'},
  {u'count': 42, u'id': 16, u'language': u'C++'},
  {u'count': 24, u'id': 15, u'language': u'C/C++ Hea...'},
  {u'count': 4, u'id': 19, u'language': u'Python'}],
 u'matchterm': u'PyUFuncObject',
 u'nextpage': 8,
 u'page': 7,
 u'previouspage': 6,
 u'query': u'PyUFuncObject',
 u'results': [],
 u'searchterm': u'PyUFuncObject',
 u'source_filters': [{u'count': 636, u'id': 2, u'source': u'Github'},
  {u'count': 61, u'id': 3, u'source': u'Bitbucket'},
  {u'count': 9, u'id': 7, u'source': u'Fedora Pr...'},
  {u'count': 7, u'id': 1, u'source': u'Google Code'}],
 u'total': 678}
```

**Comment by boyter** [comment]
Oh that is annoying.

I will have a look at the underlying logic, but I suspect your workaround approach would be correct regardless. The reason being that the total number of results is not 100% accurate. Because working out if the next page is valid would require actually generating the new page and waiting for the results I am rather reluctant to add it in.

I will have a ponder on this. Perhaps the best solution may be to update the API documentation to get around this issue unless you have some other thoughts.

**Comment by njsmith** [comment]
Yeah, the current results representation uses an abstraction that assumes you're pulling out a fixed size slice of a bigger set of results: it seems to let you request items I through I+K out of a set of N total items, with a warning when you're on the last page, and AFAICT no part of this abstraction actually matches how the underlying system works :-). The "nextpage" field lies, the "total" field is actually just a rough approximation useful for display in the UI but not for doing any reliable calculations, and when you request page I with K items then you don't actually get K items back:

```
>>> len(json.loads(s.get("https://searchcode.com/api/codesearch_I/?q=PyUFuncObject&per_page=100&p=0", verify=False).text)["results"])
94
>>> len(json.loads(s.get("https://searchcode.com/api/codesearch_I/?q=PyUFuncObject&per_page=100&p=1", verify=False).text)["results"])
83
```

So it would make sense to me to switch the abstraction to something more like Python's iterable interface, where you provide an operation that either gives you the next chunk or an error if there is none, and makes no promises about whether it will exist or what it will look like exactly...

**Comment by njsmith** [comment]
(And yeah, the easiest way to do that probably is just to update the documentation to be clear that "total" and "per_page" are approximate, and "nextpage" is just currentpage + 1, and the way you find the end is to look for an empty "results". That would successfully have saved me a bit of time :-).)

**Comment by boyter** [comment]
Right rather then dig through the code I am going to update the API documentation to reflect the current state. I will have to remember to add a test for this though as I am pretty sure it is meant to work as it states currently.

**Comment by boyter** [comment]
OK updated. Let me know if you still feel that whats written there is not clear enough and I can update it again.

**Comment by njsmith** [comment]
It looks like you now have: _Id of the offset of the next page. Is always set to +1 the current page. To determine the end or the results query till no results are returned._

I'm afraid I still find this somewhat unclear. Partly because of the "or"/"of" typo, but...

I'd write: "Id of the offset of the next page. Is always set to the current page + 1, even if you have reached the end of the results"

And then in the documentation for "results", I'd write: "If the 'results' list is empty, then this indicates that you have reached the end of the available results. To fetch all results for a given query, keep incrementing 'p' until you get a page with an empty 'results' list."

**Comment by boyter** [comment]
That's a good point. However I have used my free time for the moment... so it will remain like that for the next 9 hours or so. 

Hope its not an issue but I am going to copy that verbatim.

**Comment by boyter** [comment]
Right updated. https://searchcode.com/api/#codesearch hopefully that is a bit clearer to you and should save others from wasting any time.

Sorry about how confusing it was.
