### ISSUE TITLE
Error 500 in API

### ISSUE THREAD

**Issue by de-luca** [boyter/searchcode#32]
Got a 500 error by sending:
`https://searchcode.com/api/search_IV/?q=match.re&p=0`
instead of `?q=re.match&p=0`

**Comment by boyter** [comment]
Howdy! Not seeing any issue at the moment for this query... for either https://searchcode.com/api/search_IV/?q=rematch&p=0 or https://searchcode.com/api/search_IV/?q=matchre&p=0 both are returning 200 JSON responses. Can you confirm it its still an issue on your end?

**Comment by de-luca** [comment]
I don't know what to say, I can't get it back either.
It was a code 200 but with html (`<h1>500</h1>`) instead of json.

**Comment by boyter** [comment]
It may have been due to a scheduled restart I have configured around that time. I do that to resolve some other issues and you may have just caught it at the wrong time.

**Comment by de-luca** [comment]
Okay, thanks. I'll close as it's not a bug anymore.
