### ISSUE TITLE
Official Docker Image?

### ISSUE THREAD

**Issue by movermeyer** [boyter/searchcode#35]
As cliche as it might be, it would be nice to have an official searchcode Docker image. That way people who wanted to try out the server could just `docker run -d searchcode` and have a working searchcode server.

**Comment by movermeyer** [comment]
[Here is a basic Dockerfile that does this](https://gist.github.com/movermeyer/f40fb8878316508d38e8e64bd62d4722).

It probably needs a little bit more work in order to match the [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/).

**Comment by boyter** [comment]
Hi @movermeyer it is something I am planning on getting around to. I registered searchcode in dockerhub in anticipation of doing so. I am not an expert in docker but I agree its probably worth the effort.

Just in case you were looking for one, there is this one https://hub.docker.com/r/arkii/searchcode-server-community/ provided by @arkii however he has also asked if I would provide an official one.

**Comment by movermeyer** [comment]
Excellent. Thanks.

**Comment by arkii** [comment]
Or @boyter , you can create a docker-build repo , and setup a hook, so that docker image could be automatic build, people also can help you to maintain it.

**Comment by boyter** [comment]
That's the idea. I am not a docker expert (I have very little experience with it but will attempt to create one.

**Comment by egeland** [comment]
Hey, just curious if this ever happened? 2016 is a little while ago now.. 😉

**Comment by boyter** [comment]
I am ashamed to admit no... nothing has happened. I should look into it again.

**Comment by egeland** [comment]
Life gets in the way.. :)

**Comment by boyter** [comment]
To be honest my distractions are usually my own fault.
