### ISSUE TITLE
When refine search with languages, top tips of other languages are still displayed

### ISSUE THREAD

**Issue by tdelmas** [boyter/searchcode#36]

**Comment by boyter** [comment]
Sorry but I have to ask, could you provide the steps required to replicate this? Not sure if I can see the problem based on the current title.

**Comment by tdelmas** [comment]
Sure ! Search "statuscode", two boxes appears (not about javascript), refine results to javascript only, the results are correctly refined but the two boxes are still there :) Not a big issue, just confusing ;)

**Comment by boyter** [comment]
Ah gotcha! Yes the documentation search. I am... deprecating that functionality when I release the newer design which should be sooner rather then later. Should resolve the issue entirely :)

**Comment by tdelmas** [comment]
Indeed :)

**Comment by boyter** [comment]
Should now be resolved :)
