### ISSUE TITLE
Server Error on Space Separated Searches

### ISSUE THREAD

**Issue by umstek** [boyter/searchcode#40]
Search strings such as `ol.Map THREE`, `three openlayers` or `"three" "openlayers"` results in a `500` error.

**Comment by boyter** [comment]
Oh thats not good. It works for some such as https://searchcode.com/?q=test+junit

Investigating now.

**Comment by boyter** [comment]
Ok seems to be due to timeouts, because I dont have enough CPU grunt for this search. Going to bounce the backend servers to hopefully resolve this.

**Comment by umstek** [comment]
Thank you very much for the quick response. 😄 The site is currently down. Is that intentional?

**Comment by boyter** [comment]
Yep was rebooting the whole stack. Did not fix the issue though it seems. I need to prioritize moving over to the new code.

**Comment by boyter** [comment]
A few tweaks and this https://searchcode.com/?q=ol.Map+THREE now works. However I am moving everything over to speed this up in the long run anyway.

**Comment by umstek** [comment]
Awesome!
