### ISSUE TITLE
Case-sensitive search?

### ISSUE THREAD

**Issue by cgmb** [boyter/searchcode#41]
Is there any way to do a case-sensitive search?

**Comment by boyter** [comment]
Currently there is not. However I am in the middle of converting this over to shiny new code so its something I could investigate. You can track progress of this here https://github.com/boyter/searchcode-server/tree/searchcode

Whats the use case you have for this? Perhaps there is another way to achieve what you want?

**Comment by cgmb** [comment]
I'm investigating how frequently people use uppercase file extensions in C and C++. Mostly I want to see the number of results for uppercase and lowercase, then browse through a few of them to double-check my query isn't picking up anything unexpected.

**Comment by boyter** [comment]
So 100% currently not possible. 

What I would suggest is to use the API and page through the results to achieve this.
