### ISSUE TITLE
Indexing XML files fails

### ISSUE THREAD

**Issue by kr4cher** [boyter/searchcode#47]
XML files will not be indexed if they include any tags (empty .xml files and files with only comments are working)

I got the following error for every single xml file:
> WARNING: Thu Feb 21 09:30:50 CET 2019: QuartzScheduler_Worker-40 50: ERROR - caught a class java.lang.NullPointerException in class com.searchcode.app.jobs.repository.SearchcodeFileVisitor indexDocsByPath walkFileTree with message: null for file C:\Users\kr4cher\searchcode\test-repos\xml-files\FrontletServiceProzessaufgabeBearbeitenDescriptor.xml in path C:\Users\kr4cher\searchcode\test-repos\xml-files\FrontletServiceProzessaufgabeBearbeitenDescriptor.xml in repo eXaMpLe

**Comment by boyter** [comment]
Can you supply a sample file? I can the build it into the test suite for this.

**Comment by boyter** [comment]
Resolved over email.

**Comment by pcxxiaoxiao** [comment]
I also encountered the same problem, xml files not be indexed, can you tell me how to solve it?thanks!

**Comment by boyter** [comment]
It has been resolved if you build from master. In this case I built a special one off release to resolve it for @kr4cher 

I am still working on getting the next release ready, but if you need it sooner let me know.

**Comment by pcxxiaoxiao** [comment]
Thanks , I build from master and need the special release for development needs.

**Comment by pcxxiaoxiao** [comment]
my email: pcx19900105@163.com

**Comment by boyter** [comment]
If you are building from master and hitting the issue that is a problem.

**Comment by boyter** [comment]
Can you possibly post the file here that you are having issues with?

**Comment by pcxxiaoxiao** [comment]
The log :
WARNING: Thu May 30 03:28:53 GMT 2019: QuartzScheduler_Worker-41 52: ERROR - caught a class java.lang.NullPointerException in class com.searchcode.app.jobs.repository.SearchcodeFileVisitor indexDocsByPath walkFileTree with message: null for file ./repo/redqa_zeus/pom.xml in path ./repo/redqa_zeus/pom.xml in repo redqa_zeus

My xml file：
[pom.xml.zip](https://github.com/boyter/searchcode/files/3235336/pom.xml.zip)

I use the searchcode server community edition.

**Comment by boyter** [comment]
Thank you. I will attempt to replicate.

**Comment by boyter** [comment]
@pcxxiaoxiao I see no issue with this at all when using master. See the below screenshots where I pointed searchcode at your file without any issue.

![image](https://user-images.githubusercontent.com/612151/58768017-a0939480-85d7-11e9-8d3c-a0fe916f4379.png)
![image](https://user-images.githubusercontent.com/612151/58768021-a9846600-85d7-11e9-942b-b15fcb049f86.png)

Are you sure you a building from the most recent master? Can you post your searchcode.properties file here? I am wondering if you are running into a thread starvation issue.

**Comment by pcxxiaoxiao** [comment]
I am sure building with master.
![image](https://user-images.githubusercontent.com/4568345/58772517-ece8cf80-85eb-11e9-90fd-e9c1d0dd227f.png)

my searchcode.properties file:

# searchcode config
# If setting binary paths on windows use / not \ for directory delimiter
database=sqlite
sqlite_file=searchcode.sqlite
server_port=8080
repository_location=./repo/
index_location=./index/
facets_location=./index/facet/
trash_location=./trash/
timeindex_location=./index/time/
timeindex_facets_location=./index/time/facet/
check_repo_chages=600
check_filerepo_changes=600
only_localhost=false
low_memory=false
log_level=SEVERE
log_path=./logs
log_count=10
spelling_corrector_size=100000
max_document_queue_size=1000
max_document_queue_line_size=1000000
max_file_line_depth=10000
max_file_length_read=30000000
use_system_git=false
git_binary_path=/usr/bin/git
api_enabled=true
api_key_authentication=true
svn_enabled=false
svn_binary_path=/usr/bin/svn
owasp_database_location=./include/owasp/database.json
classifier_database_location=./include/classifier/database.json
license_database_location=./include/license/database.json
source_database_location=./include/source/database.json
highlight_lines_limit=5000
binary_guess=true
binary_extension_white_list=
binary_extension_black_list=woff,eot,cur,dm,xpm,emz,db,scc,idx,mpp,dot,pspimage,stl,dml,wmf,rvm,resources,tlb,docx,doc,xls,xlsx,ppt,pptx,msg,vsd,chm,fm,book,dgn,blines,cab,lib,obj,jar,pdb,dll,bin,out,elf,so,msi,nupkg,pyc,ttf,woff2,jpg,jpeg,png,gif,bmp,psd,tif,tiff,yuv,ico,xls,xlsx,pdb,pdf,apk,com,exe,bz2,7z,tgz,rar,gz,zip,zipx,tar,rpm,bin,dmg,iso,vcd,mp3,flac,wma,wav,mid,m4a,3gp,flv,mov,mp4,mpg,rm,wmv,avi,m4v,sqlite,class,rlib,ncb,suo,opt,o,os,pch,pbm,pnm,ppm,pyd,pyo,raw,uyv,uyvy,xlsm,swf,xz
directory_black_list=
number_git_processors=5
number_svn_processors=5
number_file_processors=5
default_and_match=true
log_indexed=false
follow_links=false
deep_guess_files=false
host_name=localhost:8080
index_all_fields=content,filename,filenamereverse,path,interesting
# The below will probably be moved into the settings page at some point in the future
password=XXX
encryption_key=XXX

**Comment by boyter** [comment]
Interesting. You might need a new build to try this out. Ill see about making you one to try.

**Comment by boyter** [comment]
@pcxxiaoxiao Can you try out this version https://searchcodeserver.com/tmp/searchcode-server-community.tar.gz built from master and let me know if it is able to index the file please.

**Comment by pcxxiaoxiao** [comment]
Ok,I will try it,Thanks!

**Comment by boyter** [comment]
@pcxxiaoxiao Any response? Otherwise I will close this due to inactivity.

**Comment by wizawu** [comment]
I have several repositories containing a file named `logback-spring.xml` but none of them is indexed.

The `searchcode-server-community.tar.gz` was downloaded two weeks ago.

**Comment by boyter** [comment]
@wizawu Same issue as above I suspect. If you build from master and don't download the latest community edition it will be resolved for you. Otherwise you can use this build https://searchcodeserver.com/tmp/searchcode-server-community.tar.gz which has the fix in it. 

I'm still working on the next release for this with no hard ETA for it. Hopefully sooner rather than later as there are a lot of good updates in there.

**Comment by wizawu** [comment]
@boyter Thank you. It works perfectly!

**Comment by boyter** [comment]
Great. Glad it was the same issue and not a new one.
